services:
  backend:
    build:
      context: ./shopper-etapa-1
    ports:
      - "3000:3000"
    networks:
      - shopper-network

  frontend:
    build:
      context: ./shopper-etapa-2
    ports:
      - "80:80"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:3000
    networks:
      - shopper-network
    depends_on:
      - backend

networks:
  shopper-network:
    driver: bridge
